using System.Collections.Generic;

// ============================================================
// QuestEvents.cs — quest event shim (quest spec §8.1)
//
// Purpose:        Thin dispatch layer that stamps contextual
//                 world-flags when quest-relevant game events
//                 occur outside narrative encounters. The quest
//                 system is a live projection over flags; this
//                 shim ensures the ~6 non-narrative event sites
//                 write the flags quest objectives gate on and
//                 returns the Snapshot-Diff toasts so the caller
//                 can push them (or discard if no toast pipe).
//
// Flag convention: "qe_<eventId>" (bare) + qualified variants
//                 "qe_<eventId>_<qualifier>" for kingdom, archmage,
//                 or building scoping. Objectives in quest JSONs
//                 gate on these flags by name.
//
// Layer:          System (static, stateless)
// Collaborators:  QuestNotifier (Snapshot/NotifyNew), GuildSaveData
//                 (SetFlag), SaveManager. Called FROM ExpeditionManager,
//                 KingdomTickSimulation, CorruptionSpread, CampusScreen.
// See:            docs/quest_system_narrative_spec_v1.md §8.1,
//                 docs/quest_hooks_compendium_v1.md §4 (triggers).
// ============================================================

/// <summary>Stamps quest-relevant world flags at game event sites and
/// returns the quest diff for the caller to toast.</summary>
public static class QuestEvents
{
    // ── Event IDs ────────────────────────────────────────────────────────
    // Used as constants in Raise() calls AND as the flag infix, so keep
    // them lowercase_snake for consistency with existing flag conventions.

    // Negotiation
    public const string NegotiationDeal     = "negotiation_deal";
    public const string NegotiationWalkaway = "negotiation_walkaway";

    // Patrol encounters
    public const string PatrolSpared    = "patrol_spared";
    public const string PatrolCompelled = "patrol_compelled";
    public const string PatrolSlain     = "patrol_slain";

    // Combat (non-dossier outcomes — dossier pass wires its own flags)
    public const string CombatWon  = "combat_won";
    public const string CombatLost = "combat_lost";

    // Siege / warfront resolution
    public const string SiegeFell     = "siege_fell";
    public const string SiegeRepelled = "siege_repelled";
    public const string SiegeSeized   = "siege_seized";
    public const string InterventionWon  = "intervention_won";
    public const string InterventionLost = "intervention_lost";

    // Corruption / blight
    public const string CorruptionAdvanced = "corruption_advanced";
    public const string ArchmageCorrupted  = "archmage_corrupted";

    // Campus
    public const string BuildingCompleted = "building_completed";

    // Archmage resolution (Step 9) — qualifier carries the archmage id, so
    // quest JSON can gate on qe_archmage_united / qe_archmage_united_{id} etc.
    public const string ArchmageUnited     = "archmage_united";
    public const string ArchmageCoerced    = "archmage_coerced";
    public const string ArchmageOverthrown = "archmage_overthrown";

    // ── Core dispatch ────────────────────────────────────────────────────

    /// <summary>
    /// Raise a quest-relevant event. Sets contextual world flags on the
    /// timeline layer (CycleState.WorldFlags) so quest objectives can gate
    /// on them, then diffs quest state and returns any resulting toasts.
    ///
    /// <para>Flags written (all idempotent via HashSet.Add):</para>
    /// <list type="bullet">
    ///   <item><c>qe_{eventId}</c> — bare event (did it happen this timeline?)</item>
    ///   <item><c>qe_{eventId}_{kingdom}</c> — kingdom-scoped (if provided)</item>
    ///   <item><c>qe_{eventId}_{qualifier}</c> — extra qualifier (archmage id,
    ///         building id, etc.)</item>
    /// </list>
    ///
    /// <para>The caller owns toasting — sites with a toast pipe push the
    /// returned list; strategic-layer sites (no pipe) discard it and the
    /// quest log picks up the change on next view.</para>
    /// </summary>
    /// <param name="eventId">One of the constants above.</param>
    /// <param name="kingdom">Optional kingdom id for scoped flags.</param>
    /// <param name="qualifier">Optional extra qualifier (archmage id,
    /// building id, etc.).</param>
    /// <returns>Quest toasts generated by the state change (may be empty).</returns>
    public static List<QuestToast> Raise(string eventId,
                                         string kingdom = null,
                                         string qualifier = null)
    {
        var save = SaveManager.ActiveSave;
        if (save == null || string.IsNullOrEmpty(eventId))
            return new List<QuestToast>();

        var before = QuestNotifier.Snapshot(save);

        // Bare event flag — "this happened at least once this timeline"
        save.SetFlag($"qe_{eventId}");

        // Kingdom-scoped flag — "this happened in/to this kingdom"
        if (!string.IsNullOrEmpty(kingdom))
            save.SetFlag($"qe_{eventId}_{kingdom}");

        // Extra qualifier — building id with tier, archmage id, etc.
        if (!string.IsNullOrEmpty(qualifier))
            save.SetFlag($"qe_{eventId}_{qualifier}");

        SaveManager.MarkDirty();
        return QuestNotifier.NotifyNew(before, save);
    }

    // ── Convenience overload with tier (campus buildings) ────────────────

    /// <summary>Raise a building event with a tier-qualified flag:
    /// <c>qe_building_completed_{buildingId}_t{tier}</c>.</summary>
    public static List<QuestToast> RaiseBuilding(string buildingId, int tier)
        => Raise(BuildingCompleted, qualifier: $"{buildingId}_t{tier}");

    // ── Toast helper (inline the push loop at call sites) ────────────────

    /// <summary>Push all quest toasts to a ToastManager, if present.
    /// Convenience for the Snapshot-Diff-Toast one-liner pattern.</summary>
    public static void PushToasts(List<QuestToast> toasts, ToastManager pipe)
    {
        if (pipe == null || toasts == null) return;
        foreach (var qt in toasts)
            pipe.Push(qt.Text, qt.Kind);
    }
}
